version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "1024mb", "--maxmemory-policy", "allkeys-lru"]

  yt-downloader:
    build: .
    container_name: yt-downloader
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
